---
- hosts: test_servers
  become: true
  tasks:
    - name: Run apt update
      ansible.builtin.apt:
        update_cache: yes

    - name: Run apt upgrade
      ansible.builtin.apt:
        upgrade: dist
